# Generated by Django 4.2.2 on 2023-06-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('no_of_users', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Direct Chat', 'Direct Chat'), ('Group Chat', 'Group Chat')], default='Direct Chat', max_length=12)),
                ('user_ids', models.ManyToManyField(related_name='chats', to='UserModel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('user_ids', models.ManyToManyField(to='UserModel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.chat')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send', to='UserModel.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receive', to='UserModel.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('no_of_admins', models.PositiveIntegerField()),
                ('no_of_users', models.PositiveIntegerField()),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media_files', models.FileField(upload_to='Group_media')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.user')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talk.chat')),
                ('user_ids', models.ManyToManyField(related_name='group_chats', to='UserModel.user')),
            ],
        ),
    ]
