# Generated by Django 4.2.2 on 2023-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='user_images/')),
                ('customlink', models.URLField(blank=True)),
                ('date_created', models.DateField()),
                ('is_verified', models.BooleanField()),
                ('rank', models.IntegerField()),
                ('no_of_groups', models.PositiveIntegerField()),
                ('group_is_admin', models.BooleanField()),
                ('no_of_group_is_admin', models.PositiveIntegerField()),
            ],
        ),
    ]
