# Generated by Django 4.2.2 on 2023-06-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('summary', models.TextField(max_length=255)),
                ('audio_file', models.FileField(blank=True, upload_to='audio_files/')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('js', models.TextField()),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('summary', models.TextField(max_length=255)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('no_of_likes', models.PositiveIntegerField()),
                ('user_uploaded', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserModel.user')),
            ],
        ),
    ]
