# Generated by Django 4.2.2 on 2023-07-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0007_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True),
        ),
    ]
