# Generated by Django 4.2.2 on 2023-06-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('params', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserModel.user')),
            ],
        ),
    ]
