<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-10 15:04
=======
# Generated by Django 4.2.2 on 2023-06-11 01:45
>>>>>>> origin/feat-000/post-feature

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
<<<<<<< HEAD
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
=======
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
>>>>>>> origin/feat-000/post-feature
                ('params', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserModel.user')),
            ],
        ),
    ]
